site_name: BSBolt (BiSulfite Bolt)

theme:
  name: 'readthedocs'
nav:
    - Home: index.md
    - Alignment: align.md
    - Methylation Calling: methylation_calling.md
    - Matrix Assembly and Imputation: matrix.md
    - Pipelines: pipelines.md
    - Simulation: simulation.md