site_name: BSBolt (BiSulfite Bolt)
repo_url: https://github.com/NuttyLogic/BSBolt
repo_name: 'GitHub'

theme:
  name: 'material'

nav:
  - Home: index.md
  - Alignment: align.md
  - Methylation Calling: methylation_calling.md
  - Matrix Assembly and Imputation: matrix.md
  - Pipelines: pipelines.md
  - Simulation: simulation.md
  - API: API.md
  - Tutorial: tutorial.md


